language: php
php:
  - '7.2'
  - '7.3'
matrix:
  allow_failures:
  - php: nightly
    
before_script: composer install --no-progress --no-interaction --no-suggest

script:
- composer cs-check
- composer phpmd
- ./vendor/bin/phpunit --coverage-clover ./test/logs/clover.xml

after_script:
- ./vendor/bin/coveralls -v
- ./vendor/bin/test-reporter -v --coverage-report=./test/logs/clover.xml
